#!/usr/bin/bash

# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# Load git keys (private key must be name github)
# Dont restart agent if already running
if [ -z "$SSH_AUTH_SOCK" ]; then
  eval "$(ssh-agent -s)" >/dev/null 2>&1
fi

# Add default SSH key (adjust path if needed)
ssh-add ~/.ssh/github >/dev/null 2>&1

export PATH="/opt/nvim/bin:$PATH"
